### ISSUE TITLE
How to properly handle indentation inside code blocks ?

### ISSUE THREAD

**Issue by Roms1383** [raphlinus/pulldown-cmark#640]
Hi and first thanks for this lib :)

I built a mdbook preprocessor for code blocks whose purpose is to prepend a tiny header on top of code blocks with e.g. the name of the language as a label and an icon. Everything works perfectly fine, even with indented markdown, but not when the code blocks is both indented and multiline.

I've been searching and experimenting on the proper way to deal with indents in pulldown-cmark but ran short, so I thought I would as well open a Discussion here (which is not active, hence why an Issue instead).

<details><summary>Here's what works fine (click to display)</summary>

---

# readme

let's try with a simple example:

```swift reds
LogChannel(n"DEBUG", "hello world");
```

```swift
print("Hello, World!") 
```

```rust
fn main() { println!("hello world"); }
```

```lua
print("Hello World")
```

```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

```yaml
some:
  interesting:
    - property
```

```json
{
  "some": { "interesting": ["property"] }
}
```

```xml
<some>
  <interesting>
    <property />
  </interesting>
</some>
```

contrary to code blocks,
`inline` and ```fenced``` are left untouched.

it should also work when deeply nested:

1. outer:
   1. inner:

      ```swift reds
      GameInstance
        .GetStatusEffectSystem(this.GetGame())
        .ApplyStatusEffect(
          this.GetEntityID(),
          t"BaseStatusEffect.SplinterAddicted",
          this.GetRecordID(),
          this.GetEntityID());
      ```
</details>

<details><summary>And here's what typically not (click to display)</summary>

- WolvenKit :
  - open *splinter_buff.effect* in project
    - rename it e.g. *splinter_addicted.effect*
    - move it e.g. *fx\camera\splinter_addicted\splinter_addicted.effect*
  - open *base\characters\entities\player\player_wa_fpp.ent* in project
    - add a new entry under components.fx_player.effectDescs
    - fill the previously created file info and effectName desired in RED
      you can then call it with e.g.

      ```swift
      GameObjectEffectHelper.StartEffectEvent(this, n"splinter_addicted");
      ```

      even create e.g. a YAML tweak

      ```yaml
      BaseStatusEffect.SplinterAddicted:
        $base: BaseStatusEffect.FirstAidWhiffV0
        packages: []
        VFX:
          - $type: StatusEffectFX_Record
            name: splinter_addicted
            shouldReapply: true
      ```

      then call it with e.g.

      ```swift
      GameInstance
        .GetStatusEffectSystem(this.GetGame())
        .ApplyStatusEffect(this.GetEntityID(), t"BaseStatusEffect.SplinterAddicted", this.GetRecordID(), this.GetEntityID());
      ```

</details>
